# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: oci-kvm-hook.spec

# add or remove files that should be synced
synced_files:
    - oci-kvm-hook.spec
    - .packit.yaml

# name in upstream package repository/registry (e.g. in PyPI)
upstream_package_name: oci-kvm-hook
# downstream (Fedora) RPM package name
downstream_package_name: oci-kvm-hook

jobs:
- job: copr_build
  trigger: pull_request
  metadata:
    targets:
    - fedora-all
    - centos-stream-x86_64
